### ISSUE TITLE
Add File Storage

### ISSUE THREAD

**Issue by Willie169** [Bandeapart1964/PuppyGit#6]
Can it access storages such as app directory (e.g. /data/data/com.termux/files/home) or SFTP/FTP/WebDAV/SMB server?

**Comment by Bandeapart1964** [comment]
> Can it access storages such as app directory (e.g. /data/data/com.termux/files/home) or SFTP/FTP/WebDAV/SMB server?

Can't, /data/data/xxx need higher permission, SFTP/WEBDAV etc no plan support

**Comment by Willie169** [comment]
Thanks.

**Comment by Bandeapart1964** [comment]
> Thanks. 

You are welcome

 btw , even no plan support ftp, but I have plan support puppygit work with termux
